# Generated by Django 5.0.3 on 2024-03-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0003_alter_message_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images'),
        ),
    ]
