# Generated by Django 5.0.3 on 2024-03-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0004_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
